name: Continious integration

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests and upload results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21", "1.22"]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # This is currently workaround for checking if gofiles have changed,
      # Because paths filter doesn't work with required checks
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf # v45
        with:
          files: |
            cmd/**
            internal/**
            .golangci.yml
            go.mod
            go.sum

      - name: Setup Go
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6
        with:
          version: latest
          args: --timeout=5m

      - name: Install dependencies
        if: steps.changed-files.outputs.any_modified == 'true'
        run: go mod download

      - name: Test with Go
        if: steps.changed-files.outputs.any_modified == 'true'
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: codecov/codecov-action@985343d70564a82044c1b7fcb84c2fa05405c1a2 # v5.0.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cover.txt
          slug: bl4ko/netbox-ssot

  vulnerabilities:
    name: Check for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf # v45
        with:
          files: |
            cmd/**
            internal/**
            .golangci.yml
            go.mod
            go.sum
            .dockerignore
            Dockerfile

      - name: Run Trivy vulnerability scanner
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
